In [2]:
import pandas as pd

In [3]:
matches=pd.read_csv("./datasets/dim_match_summary.csv")
matches.head()

         team1        team2       winner     margin     matchDate match_id
0  Super Kings          KKR  Super Kings    27 runs  Oct 15, 2021  T203817
1     Capitals          KKR          KKR  3 wickets  Oct 13, 2021  T206442
2          RCB          KKR          KKR  4 wickets  Oct 11, 2021  T208597
3     Capitals  Super Kings  Super Kings  4 wickets  Oct 10, 2021  T201819
4     Capitals          RCB          RCB  7 wickets   Oct 8, 2021  T205942

In [4]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team1      206 non-null    object
 1   team2      206 non-null    object
 2   winner     206 non-null    object
 3   margin     206 non-null    object
 4   matchDate  206 non-null    object
 5   match_id   206 non-null    object
dtypes: object(6)
memory usage: 9.8+ KB

In [5]:
matches.isnull().sum()

team1        0
team2        0
winner       0
margin       0
matchDate    0
match_id     0
dtype: int64

In [6]:
matches.tail()

            team1      team2        winner     margin     matchDate match_id
201        Mumbai        RCB           RCB  8 wickets   Apr 2, 2023  T202485
202        Royals  Sunrisers        Royals    72 runs   Apr 2, 2023  T209117
203  Super Giants   Capitals  Super Giants    50 runs   Apr 1, 2023  T208512
204  Punjab Kings        KKR  Punjab Kings     7 runs   Apr 1, 2023  T202853
205   Super Kings     Titans        Titans  5 wickets  Mar 31, 2023  T201566

In [7]:
matches.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Length: 206, dtype: bool

Remember:The 'inplace = True' will make sure that

In [8]:
matches.drop_duplicates(inplace=True)

In [9]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team1      206 non-null    object
 1   team2      206 non-null    object
 2   winner     206 non-null    object
 3   margin     206 non-null    object
 4   matchDate  206 non-null    object
 5   match_id   206 non-null    object
dtypes: object(6)
memory usage: 9.8+ KB

In [10]:
#most successful team
top_teams = matches['winner'].value_counts().head()
top_teams

winner
Super Kings    25
RCB            25
Titans         23
Royals         22
KKR            21
Name: count, dtype: int64

In [11]:
#close matches
close_matches = matches[(matches['margin'].str.contains('run'))&(matches['margin'].str.extract('(\d)').astype(int)<10)].any(axis=1)
close_matches

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\tamra\AppData\Local\Temp\ipykernel_19712\2590406690.py:2: SyntaxWarning: invalid escape sequence '\d'
  close_matches = matches[(matches['margin'].str.contains('run'))&(matches['margin'].str.extract('(\d)').astype(int)<10)].any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
201    False
202    False
203    False
204    False
205    False
Length: 206, dtype: bool

In [12]:
batting= pd.read_csv("./datasets/fact_bating_summary.csv")
players=pd.read_csv("./datasets/dim_players.csv")

In [13]:
batting.head()

,match_id,match,teamInnings,battingPos,batsmanName,out/not_out,runs,balls,4s,6s,SR
0,T203817,Super Kings Vs KKR,Super Kings,1,RuturajGaikwad,out,32,27,3,1,118.51
1,T203817,Super Kings Vs KKR,Super Kings,2,FafduPlessis,out,86,59,7,3,145.76
2,T203817,Super Kings Vs KKR,Super Kings,3,RobinUthappa,out,31,15,0,3,206.66
3,T203817,Super Kings Vs KKR,Super Kings,4,MoeenAli,not_out,37,20,2,3,185.00
4,T203817,Super Kings Vs KKR,KKR,1,ShubmanGill,out,51,43,6,0,118.60

In [14]:
players.head()

,name,team,battingStyle,bowlingStyle,playingRole
0,RuturajGaikwad,Super Kings,Right hand Bat,Right arm Offbreak,Batter
1,FafduPlessis,Super Kings,Right hand Bat,Legbreak,Middle order Batter
2,RobinUthappa,Super Kings,Right hand Bat,Right arm Medium,Batter
3,MoeenAli,Super Kings,Left hand Bat,Right arm Offbreak,Batting Allrounder
4,ShubmanGill,KKR,Right hand Bat,Right arm Offbreak,Opening Batter

In [15]:
#top runs scorers:
top_scorers=(batting.groupby('batsmanName')["runs"].sum().reset_index().sort_values(by='runs',ascending=False).head(10))
top_scorers

         batsmanName  runs
222      ShubmanGill  1851
66      FafduPlessis  1831
197   RuturajGaikwad  1593
97           KLRahul  1516
95        JosButtler  1509
216    ShikharDhawan  1392
251       ViratKohli  1385
204      SanjuSamson  1304
230  SuryakumarYadav  1225
69      GlennMaxwell  1214

In [16]:
merged=top_scorers.merge(players,left_on='batsmanName',right_on='name')

In [17]:
merged

,batsmanName,runs,name,team,battingStyle,bowlingStyle,playingRole
0,ShubmanGill,1851,ShubmanGill,KKR,Right hand Bat,Right arm Offbreak,Opening Batter
1,FafduPlessis,1831,FafduPlessis,Super Kings,Right hand Bat,Legbreak,Middle order Batter
2,RuturajGaikwad,1593,RuturajGaikwad,Super Kings,Right hand Bat,Right arm Offbreak,Batter
3,KLRahul,1516,KLRahul,Punjab Kings,Right hand Bat,Not Available,Wicketkeeper Batter
4,JosButtler,1509,JosButtler,Royals,Right hand Bat,Not Available,Wicketkeeper Batter
5,ShikharDhawan,1392,ShikharDhawan,Capitals,Left hand Bat,Right arm Offbreak,Opening Batter
6,ViratKohli,1385,ViratKohli,RCB,Right hand Bat,Right arm Medium,Top order Batter
7,SanjuSamson,1304,SanjuSamson,Royals,Right hand Bat,Not Available,Wicketkeeper Batter
8,SuryakumarYadav,1225,SuryakumarYadav,Mumbai,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter
9,GlennMaxwell,1214,GlennMaxwell,RCB,Right hand Bat,Right arm Offbreak,Batting Allrounder

In [18]:
bowling=pd.read_csv("./datasets/fact_bowling_summary.csv")

In [19]:
#top wicket takers
top_wickets=(bowling.groupby('bowlerName')["wickets"].sum().reset_index().sort_values(by='wickets',ascending=False).head(10))
top_wickets

            bowlerName  wickets
110      MohammedShami       67
201    YuzvendraChahal       66
54        HarshalPatel       65
141         RashidKhan       63
20           AveshKhan       47
19       ArshdeepSingh       45
75        KagisoRabada       45
189  VarunChakravarthy       44
163      ShardulThakur       43
181         TrentBoult       42

In [20]:
#Best economy (with condition)
economy=(bowling.groupby)

In [21]:
#1. Top 10 batsmen based on past 3 years total runs scored.

top10_batsmen = (batting.groupby('batsmanName')["runs"].sum()
                .reset_index()
                .sort_values(by='runs', ascending=False)
                .head(10))

top10_batsmen

         batsmanName  runs
222      ShubmanGill  1851
66      FafduPlessis  1831
197   RuturajGaikwad  1593
97           KLRahul  1516
95        JosButtler  1509
216    ShikharDhawan  1392
251       ViratKohli  1385
204      SanjuSamson  1304
230  SuryakumarYadav  1225
69      GlennMaxwell  1214

In [22]:
#2. Top 10 batsmen based on past 3 years batting average. (min 60 balls faced in each 
#season) 
bat_agg = (batting.groupby("batsmanName")
                  .agg(runs=("runs","sum"),
                       balls=("balls","sum"),
                      ))
finishers = (bat_agg.query("balls >= 100")
                    .assign(batting_average=lambda x:  x["runs"] / x["balls"])
                    .sort_values("batting_average", ascending=False)
                    .head(10))
print(finishers[["runs","balls","batting_average"]])

                 runs  balls  batting_average
batsmanName
TimDavid          418    235         1.778723
HeinrichKlaasen   448    253         1.770751
RashidKhan        304    172         1.767442
LiamLivingstone   758    452         1.676991
PhilSalt          218    133         1.639098
GlennMaxwell     1214    752         1.614362
SuryakumarYadav  1225    763         1.605505
CameronGreen      452    282         1.602837
JiteshSharma      543    341         1.592375
AndreRussell      745    468         1.591880

In [23]:
#3.. Top 10 batsmen based on past 3 years strike rate (min 60 balls faced in each 
#season)
bat_agg = (batting.groupby("batsmanName")
                  .agg(runs=("runs","sum"),
                       balls=("balls","sum"),
                      ))
finishers = (bat_agg.query("balls >= 100")
                    .assign(strike_rate=lambda x: 60 * x["runs"] / x["balls"])
                    .sort_values("strike_rate", ascending=False)
                    .head(10))
print(finishers[["runs","balls","strike_rate"]])

                 runs  balls  strike_rate
batsmanName
TimDavid          418    235   106.723404
HeinrichKlaasen   448    253   106.245059
RashidKhan        304    172   106.046512
LiamLivingstone   758    452   100.619469
PhilSalt          218    133    98.345865
GlennMaxwell     1214    752    96.861702
SuryakumarYadav  1225    763    96.330275
CameronGreen      452    282    96.170213
JiteshSharma      543    341    95.542522
AndreRussell      745    468    95.512821

In [24]:
#4. Top 10 bowlers based on past 3 years total wickets taken. 
import pandas as pd
matches = pd.read_csv("./Datasets/fact_bowling_summary.csv")
top10_bowler = (matches.groupby('bowlerName')["wickets"].sum()
                .reset_index()
                .sort_values(by='wickets', ascending=False)
                .head(10))

top10_bowler

            bowlerName  wickets
110      MohammedShami       67
201    YuzvendraChahal       66
54        HarshalPatel       65
141         RashidKhan       63
20           AveshKhan       47
19       ArshdeepSingh       45
75        KagisoRabada       45
189  VarunChakravarthy       44
163      ShardulThakur       43
181         TrentBoult       42

In [25]:
#5. Top 10 bowlers based on past 3 years bowling average. (min 60 balls bowled in each 
#season).
import pandas as pd
matches = pd.read_csv("./Datasets/fact_bowling_summary.csv")
bowl_agg = (bowling.groupby("bowlerName")
                  .agg(runs=("runs","sum"),
                       overs=("overs","sum"),
                       wickets=("wickets","sum"),
                      ))
finishers = (bowl_agg.query("overs >= 10")
                    .assign(bowler_average=lambda x:  x["runs"] / x["overs"])
                    .sort_values("bowler_average", ascending=False)
                    .head(10))
print(finishers[["runs","overs","wickets","bowler_average"]])

                  runs  overs  wickets  bowler_average
bowlerName
ArshadKhan         190   13.7        5       13.868613
RiyanParag         132   10.1        2       13.069307
NavdeepSaini       198   16.0        6       12.375000
OdeanSmith         178   15.0        6       11.866667
ShreyasGopal       118   10.0        1       11.800000
AkashDeep          264   23.5        6       11.234043
TymalMills         190   17.0        6       11.176471
KartikTyagi        295   27.7        6       10.649819
JhyeRichardson     117   11.0        3       10.636364
VijaykumarVyshak   253   24.0        9       10.541667

In [27]:
#6. Top 10 bowlers based on past 3 years economy rate. (min 60 balls bowled in each 
#season).

economy = (bowling.groupby('bowlerName')
            .agg({'overs': "sum", 'runs': 'sum'})
            .query('overs > 10')
            .assign(economy=lambda x: x['runs'] / x['overs'])
            .sort_values(by='economy')
            .reset_index()
            .head(10)
            )

economy

        bowlerName  overs  runs   economy
0      SunilNarine  160.0  1056  6.600000
1  MitchellSantner   31.0   211  6.806452
2      DavidWilley   26.0   177  6.807692
3       MohsinKhan   43.0   304  7.069767
4         MoeenAli   70.7   501  7.086280
5        AxarPatel  132.0   939  7.113636
6    ShakibAlHasan   26.0   187  7.192308
7       RashidKhan  182.5  1317  7.216438
8    JaspritBumrah  108.2   793  7.329020
9      JayantYadav   21.0   156  7.428571

In [39]:
#7. Top 5 batsmen based on past 3 years boundary % (fours and sixes). 
top5_batsmen = (batting.groupby('batsmanName')
                .agg({'4s': 'sum', '6s': 'sum', 'balls': 'sum'})
                .query('balls > 100')
                .assign(boundary_percentage=lambda x: (x['4s'] + x['6s']) / x['balls'] * 100)
                .sort_values(by='boundary_percentage', ascending=False)
                .reset_index()
                .head(5)
                )
print(top5_batsmen)

       batsmanName   4s  6s  balls  boundary_percentage
0       RashidKhan   20  24    172            25.581395
1         PhilSalt   24  10    133            25.563910
2  YashasviJaiswal  142  46    744            25.268817
3      PrithviShaw  102  28    532            24.436090
4        EvinLewis   26  10    149            24.161074

In [41]:
#8. Top 5 bowlers based on past 3 years dot ball %.
import pandas as pd
matches = pd.read_csv("./Datasets/fact_bowling_summary.csv") 
top5_bowlers = (bowling.groupby('bowlerName')
                .agg({'0s': 'sum', 'balls': 'sum'})
                .query('balls > 100')
                .assign(dot_ball_percentage=lambda x: x['0s'] / x['balls'] * 100)
                .sort_values(by='dot_ball_percentage', ascending=False)
                .reset_index()
                .head(5)
                )
print(top5_bowlers[['bowlerName','balls','0s','dot_ball_percentage']])

KeyError: "Column(s) ['balls'] do not exist"

In [31]:
#9.Top 4 teams based on past 3 years winning %.  
top_winners = matches['winner'].value_counts().head(5)
top_winners

KeyError: 'winner'

In [ ]:
#10.Top 2 teams with the highest number of wins achieved by chasing targets over the 
#past 3 years.